name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Test
      run: cargo test
    - name: Test Chrome/Firefox
      run: wasm-pack test --headless --chrome --firefox
  test-safari:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Test Safari
      run: wasm-pack test --headless --safari
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test, test-safari]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO_TOKEN }}
        dry-run: true